name: Sync to Hugging Face hub

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Alam7324:$HF_TOKEN@huggingface.co/spaces/Alam7324/College-Placement-Predictor HEAD:main